### ISSUE TITLE
Wrong Fabric Loader Type

### ISSUE THREAD

**Issue by Melatonink** [Up-Mods/Icarae-Origin#1]
Hi! I recently downloaded this mod to add to a pre-existing modpack (BCG+), but it uses Fabric Loader 0.14.25. Is there any way I can alter the mod so it can be compatible on this version of Fabric? If not, that's totally okay!

![image_2024-05-02_112543010](https://github.com/Up-Mods/Icarae-Origin/assets/168771878/11da387a-439e-4ef1-b2e9-f39b05366a64)

**Comment by CammiePone** [comment]
cant promise it'll actually work, but Fabric and Quilt have a way to override dependency version requirements 

https://fabricmc.net/wiki/tutorial:dependency_overrides

**Comment by UpcraftLP** [comment]
> Hi! I recently downloaded this mod to add to a pre-existing modpack (BCG+), but it uses Fabric Loader 0.14.25. Is there any way I can alter the mod so it can be compatible on this version of Fabric? If not, that's totally okay!

Just update the version of fabric loader you are using.
